import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Script from "next/script"
import { OtherWalletProvider } from "src/contexts/OtherWalletContext"
import { ToastProvider } from "src/contexts/ToastContext"

export const metadata: Metadata = {
  applicationName: "Lockbox Demo",
  title: "Lockbox Demo",
  description: "Generated by Next.js",
  authors: [{ name: "Sky Mavis", url: "https://skymavis.com" }],

  icons: "https://cdn.skymavis.com/explorer-cdn/asset/fav.ico",
}

const interFont = Inter({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
})

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={interFont.className}>
      <body>
        <main>
          <OtherWalletProvider>
            <ToastProvider>{children}</ToastProvider>
          </OtherWalletProvider>
        </main>
      </body>

      <Script src="https://accounts.google.com/gsi/client" />
    </html>
  )
}

export default RootLayout
