import "./globals.css"

import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import { Toaster } from "src/@/components/ui/toaster"
import { cn } from "src/@/lib/utils"
import { WalletContext } from "src/contexts/WalletContext"

export const metadata: Metadata = {
  applicationName: "Mavis ID Playground",
  title: "ID Playground",
  description: "Generated by Next.js",
  authors: [{ name: "Sky Mavis", url: "https://skymavis.com" }],

  icons: "https://cdn.skymavis.com/explorer-cdn/asset/fav.ico",
}

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <main>
          <WalletContext>{children}</WalletContext>
        </main>
        <Toaster />
      </body>
    </html>
  )
}

export default RootLayout
