// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file rpc/proto/v1/sign.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rpc/proto/v1/sign.proto.
 */
export const file_rpc_proto_v1_sign: GenFile = /*@__PURE__*/
  fileDesc("ChdycGMvcHJvdG8vdjEvc2lnbi5wcm90bxIMcnBjLnByb3RvLnYxIkMKC1NpZ25SZXF1ZXN0EiQKBHR5cGUYASABKA4yFi5ycGMucHJvdG8udjEuU2lnblR5cGUSDgoGcGFyYW1zGAIgASgMIh4KDFNpZ25SZXNwb25zZRIOCgZyZXN1bHQYASABKAwiKgoXU2VuZFRyYW5zYWN0aW9uUmVzcG9uc2USDwoHdHhfaGFzaBgBIAEoCSpXCghTaWduVHlwZRIZChVTSUdOX1RZUEVfVU5TUEVDSUZJRUQQABIVChFTSUdOX1RZUEVfTUVTU0FHRRABEhkKFVNJR05fVFlQRV9UUkFOU0FDVElPThACQj1aO2dpdGh1Yi5jb20vYXhpZWluZmluaXR5L3gtc2VydmljZS9nZW4vZ28vcnBjL3Byb3RvL3YxO3JwY3YxYgZwcm90bzM");

/**
 * @generated from message rpc.proto.v1.SignRequest
 */
export type SignRequest = Message<"rpc.proto.v1.SignRequest"> & {
  /**
   * @generated from field: rpc.proto.v1.SignType type = 1;
   */
  type: SignType;

  /**
   * @generated from field: bytes params = 2;
   */
  params: Uint8Array;
};

/**
 * Describes the message rpc.proto.v1.SignRequest.
 * Use `create(SignRequestSchema)` to create a new message.
 */
export const SignRequestSchema: GenMessage<SignRequest> = /*@__PURE__*/
  messageDesc(file_rpc_proto_v1_sign, 0);

/**
 * @generated from message rpc.proto.v1.SignResponse
 */
export type SignResponse = Message<"rpc.proto.v1.SignResponse"> & {
  /**
   * @generated from field: bytes result = 1;
   */
  result: Uint8Array;
};

/**
 * Describes the message rpc.proto.v1.SignResponse.
 * Use `create(SignResponseSchema)` to create a new message.
 */
export const SignResponseSchema: GenMessage<SignResponse> = /*@__PURE__*/
  messageDesc(file_rpc_proto_v1_sign, 1);

/**
 * @generated from message rpc.proto.v1.SendTransactionResponse
 */
export type SendTransactionResponse = Message<"rpc.proto.v1.SendTransactionResponse"> & {
  /**
   * @generated from field: string tx_hash = 1;
   */
  txHash: string;
};

/**
 * Describes the message rpc.proto.v1.SendTransactionResponse.
 * Use `create(SendTransactionResponseSchema)` to create a new message.
 */
export const SendTransactionResponseSchema: GenMessage<SendTransactionResponse> = /*@__PURE__*/
  messageDesc(file_rpc_proto_v1_sign, 2);

/**
 * @generated from enum rpc.proto.v1.SignType
 */
export enum SignType {
  /**
   * @generated from enum value: SIGN_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SIGN_TYPE_MESSAGE = 1;
   */
  MESSAGE = 1,

  /**
   * @generated from enum value: SIGN_TYPE_TRANSACTION = 2;
   */
  TRANSACTION = 2,
}

/**
 * Describes the enum rpc.proto.v1.SignType.
 */
export const SignTypeSchema: GenEnum<SignType> = /*@__PURE__*/
  enumDesc(file_rpc_proto_v1_sign, 0);

