// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file rpc/proto/v1/message.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file rpc/proto/v1/message.proto.
 */
export const file_rpc_proto_v1_message: GenFile = /*@__PURE__*/
  fileDesc("ChpycGMvcHJvdG8vdjEvbWVzc2FnZS5wcm90bxIMcnBjLnByb3RvLnYxIkAKB01lc3NhZ2USJwoEdHlwZRgBIAEoDjIZLnJwYy5wcm90by52MS5NZXNzYWdlVHlwZRIMCgRkYXRhGAIgASgMKq0BCgtNZXNzYWdlVHlwZRIdChlQQVlFUl9NRVNTQUdFX1VOU1BFQ0lGSUVEEAASIAocUEFZRVJfTUVTU0FHRV9HRU5FUkFURV9OT05DRRABEh4KGlBBWUVSX01FU1NBR0VfQUNDRVNTX1RPS0VOEAISIQodUEFZRVJfTUVTU0FHRV9QQVlFUl9TSUdOQVRVUkUQChIaChZTRU5EX01FU1NBR0VfU0lHTl9IQVNIEGRCPVo7Z2l0aHViLmNvbS9heGllaW5maW5pdHkveC1zZXJ2aWNlL2dlbi9nby9ycGMvcHJvdG8vdjE7cnBjdjFiBnByb3RvMw");

/**
 * @generated from message rpc.proto.v1.Message
 */
export type Message = Message$1<"rpc.proto.v1.Message"> & {
  /**
   * @generated from field: rpc.proto.v1.MessageType type = 1;
   */
  type: MessageType;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message rpc.proto.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message> = /*@__PURE__*/
  messageDesc(file_rpc_proto_v1_message, 0);

/**
 * @generated from enum rpc.proto.v1.MessageType
 */
export enum MessageType {
  /**
   * @generated from enum value: PAYER_MESSAGE_UNSPECIFIED = 0;
   */
  PAYER_MESSAGE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PAYER_MESSAGE_GENERATE_NONCE = 1;
   */
  PAYER_MESSAGE_GENERATE_NONCE = 1,

  /**
   * @generated from enum value: PAYER_MESSAGE_ACCESS_TOKEN = 2;
   */
  PAYER_MESSAGE_ACCESS_TOKEN = 2,

  /**
   * @generated from enum value: PAYER_MESSAGE_PAYER_SIGNATURE = 10;
   */
  PAYER_MESSAGE_PAYER_SIGNATURE = 10,

  /**
   * @generated from enum value: SEND_MESSAGE_SIGN_HASH = 100;
   */
  SEND_MESSAGE_SIGN_HASH = 100,
}

/**
 * Describes the enum rpc.proto.v1.MessageType.
 */
export const MessageTypeSchema: GenEnum<MessageType> = /*@__PURE__*/
  enumDesc(file_rpc_proto_v1_message, 0);

