name: Security and Build

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build for PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: Setup pnpm
        shell: bash
        run: corepack enable pnpm && corepack use pnpm@9.1.1

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_READ_TOKEN }}

      - name: Build
        run: pnpm build
